# Chapter 3 - Basic Math and Statistics
## Segment 1 - Using NumPy to perform arithmetic operations on data

In [2]:
import numpy as np
from numpy.random import randn

In [3]:
np.set_printoptions(precision=2)


## Creating arrays
### Creating arrays using a list

In [4]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
b = np.array([[10,20,20], [30,40,50]])
b


array([[10, 20, 20],
       [30, 40, 50]])

### Creating arrays via assignment

In [6]:
np.random.seed(25)
c = np.random.randn(6)
c


array([ 0.23,  1.03, -0.84, -0.59, -0.96, -0.22])

In [7]:
d = np.arange(1, 35)


## Performing arthimetic on arrays

In [8]:
a*10


array([10, 20, 30, 40, 50, 60])

In [9]:
c - a


array([-0.77, -0.97, -3.84, -4.59, -5.96, -6.22])

In [10]:
c + a


array([1.23, 3.03, 2.16, 3.41, 4.04, 5.78])

In [11]:
c / a

array([ 0.23,  0.51, -0.28, -0.15, -0.19, -0.04])

### Multiplying matrices and basic linear algebra

In [12]:
np.set_printoptions(precision=2)

In [13]:
aa = np.array([[2.,4.,6.], [1.,3.,5.], [10.,20.,30.]])
bb = np.array([[0.,1.,2.], [3.,4.,5.], [6.,7.,8.]])


In [14]:
aa * bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [17]:
np.dot(aa, bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])